version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: sistema-avicola-backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - SUPABASE_URL=https://raedaqgefjftnmpaqfcr.supabase.co
      - SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJhZWRhcWdlZmpmdG5tcGFxZmNyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyMzg5MzIsImV4cCI6MjA1OTgxNDkzMn0.sQbBsMcy_i2o72WZMZvjwIkWAXdkDOWLzEyeRqc68cU
      - SUPABASE_SERVICE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJhZWRhcWdlZmpmdG5tcGFxZmNyIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc0NDIzODkzMiwiZXhwIjoyMDU5ODE0OTMyfQ.Rp9s4efxBg8uKgWt0S6NfVr2gc3XINjvqC4ogWgjgKw
      - JWT_SECRET=sistema_avicola_ieci_super_secreto_2024_no_compartir_nunca_123456789
      - ALLOWED_ORIGINS=http://localhost:1705,http://frontend:80,http://127.0.0.1:1705
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:5000/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=http://localhost:5000
    container_name: sistema-avicola-frontend
    ports:
      - "1705:80"
    environment:
      - VITE_API_URL=http://localhost:5000
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - app-network
    restart: unless-stopped
    # Health check más simple y confiable
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 45s

networks:
  app-network:
    driver: bridge
    name: sistema-avicola-network
