version: '3.8'

services:
  backend:
    build: ./backend
    container_name: backend-app
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    restart: always

  frontend:
    build: ./frontend
    container_name: frontend-app
    ports:
      - "1705:80"  # usa 1705 como en tu servidor real
    restart: always
